<html
lang="pt"
class="light-style layout-menu-fixed">
 <body>
  <!-- Layout wrapper -->
  <div class="layout-wrapper layout-content-navbar">
    <div class="layout-container">
      <!-- / Layout page -->
        <div class="layout-page">
          <!-- Content wrapper -->
          <div class="content-wrapper">
            <!-- Content -->

            <div class="container-xxl flex-grow-1 container-p-y">
              <div class="row">
              
              </div>
                
                <!--/ Total Revenue -->
                <div>
                  <div class="row">
                  <div class="col-12">
                  <div class="card mb-3">
                    <h5 class="card-header" align="center">Centro de Custo</h5>
                    <div class="card-body row">
                      <div align="left">
                        <label class="form-label">
                          <h5>Filtros:</h5>
                        </label>
                      </div>
                      <div class=" col-4 mb-3">
                        <label for="exampleFormControlSelect1" class="form-label">Status:</label>
                        <select class="form-select" id="exampleFormControlSelect1" aria-label="Default select example">
                          <option selected>Selecione um Status</option>
                          <option value="1">Ativo</option>
                          <option value="2">Inativo</option>
                        </select>
                        </br>
                        <div class="mb-1" align="left">
                          <label class="form-label">
                            <button class="btn btn-primary">Aplicar Filtro</button>
                          </label>
                      </div>
                      </div>
                      <div class="col-4 mb-3">
                        <label for="exampleFormControlSelect1" class="form-label">Tipo:</label>
                        <select class="form-select" id="exampleFormControlSelect1" aria-label="Default select example">
                          <option selected>Selecione um Tipo</option>
                          <option value="Entrada/Saida">Entrada/Saida</option>
                          <option value="1">Entrada</option>
                          <option value="2">Saida</option>
                        </select>
                      </div>
                      <div class="col-4 mb-3">
                        <label for="exampleFormControlSelect1" class="form-label">Atividade</label>
                        <select class="form-select" id="exampleFormControlSelect1" aria-label="Default select example">
                          <option selected>Selecione uma Atividade:</option>
                          <option value="1">Odontologia</option>
                          <option value="2">Fisioterapia</option>
                        </select>
                      </div>
                    </div>
                    <!-- botoes ação origens -->
                    <div class="row card-body">
                      <div class="col-4">
                        <button class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#modal_cadastro_centrodeCusto">Cadastro Centro de Custo</button>
                      </div>
                    </div>
                    <!-- inicio Tabela -->
                    <h5 class="card-header">Centro de Custo Cadastradas</h5>
                        <div class="table-responsive text-nowrap">
                            <table class="table">
                            <thead>
                            <tr>
                                <th>Nome</th>
                                <th>Atividade</th>
                                <th>Tipo</th>
                                <th>Status</th>
                            
                            </tr>
                            </thead>
                            <tbody>
                              <?php foreach($this->view->tb_centrodecustos as $id_centrodecusto => $tb_centrodecustos) { ?>
                                <tr>
                                   <td><?= $tb_centrodecustos['nome_centrodecusto'] ?></td>
                                   <td><?= $tb_centrodecustos['atividade_centrodecusto'] ?></td>
                                   <td><?= $tb_centrodecustos['tipo_centrodecusto'] ?></td>
                                   <?php 
                                     switch ($tb_centrodecustos['status_centrodecusto']) {
                                         case 'Ativo':
                                             $cor = 'class="badge bg-label-success me-1"';
                                             break;
                                         case 'Inativo':
                                             $cor = 'class="badge bg-label-warning me-1"';
                                             break;
                                         case 'Orçamento':
                                             $cor = '#CDB380';
                                             break;
                                         case 'Negociação':
                                             $cor = '#AEB404';
                                             break;
                                         case 'Cancelado':
                                             $cor = '#CD0000';
                                             break;
                                         case 'Finalizado':
                                             $cor = '#256';
                                             break;
                                         case 'Faturado':
                                             $cor = '#B266FF';
                                             break;
                                         case 'Aguardando Peças':
                                             $cor = '#FF7F00';
                                             break;
                                         case 'Aprovado':
                                             $cor = '#808080';
                                             break;
                                         default:
                                             $cor = '#E0E4CC';
                                             break;
                                           } 
 
                                           echo '<td><span '. $cor .'>' . $tb_centrodecustos['status_centrodecusto'] . '</span> </td>';
 
                                           ?>
                                
                                 </tr>
                                <?php } ?>
                            </tbody>
                            </table>
                    <!-- Final Tabela -->
                        </div>
                    </div>
                </div>
              </div>    
          </div>
        <!-- / Content wrapper -->
          
      <!-- / Layout page -->
         </div>

         <!-- Modal -->
                
         <div class="modal fade" id="modal_cadastro_centrodecusto" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
          <div class="modal-dialog">
            <div class="modal-content">
              <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">Cadastro Centro de Custo</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
              </div>
              <form method="post" action="/centro_custo"> 
              <div class="modal-body">
                               
              <div class="row">
                <div class="col mb-3">
                            <label class="form-label">Nome:</label>
                            <input
                              type="text"
                              name="nome_centrodecusto"
                              class="form-control"
                              />
                </div>
                <div class="mb-3">
                            <label class="form-label">Atividade:</label>
                             <select class="form-select" name="atividade_centrodecusto">
                                <option value="">Selecione uma Atividade</option>
                                <option value="comun">Atividade Comun</option>
                                <option value="Odontologia">Odontologia</option>
                                <option value="Fisioterapia">Fisioterapia</option>
                            </select>
                </div>
                <div class="mb-3">
                            <label class="form-label">Tipo:</label>
                            <select class="form-select" name="tipo_centrodecusto">
                              <option value="Entrada/Saida">Entrada/Saida</option>
                              <option value="Entrada">Entrada</option>
                              <option value="Saida">Saida</option>
                            </select>
                </div>
                <div class="mb-3">
                  <label class="form-label">Status:</label>
                      <select class="form-select" name="status_centrodecusto">
                        <option value="Ativo">Ativo</option>
                        <option value="Inativo">Inativo</option>
                      </select>
                </div>
              </div>
              </div>
              <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Calcelar</button>
                <button type="submit" class="btn btn-primary">Salvar</button>
              </div>
              
                </form>
            </div>
          
          </div>
        </div>
    </div>
</body>
</html>
