<!-- Layout container -->
<div class="layout-page">
  <!-- Navbar -->

  <!-- Content wrapper -->
  <div class="content-wrapper">
    <!-- Content -->

    <div class="container-xxl flex-grow-1 container-p-y">
      <div class="row">
      
      </div>
        
        <!--/ Total Revenue -->
        <div>
          <div class="row">
          <div class="col-12">
          <div class="card mb-3">
            <h5 class="card-header" align="center">Pagamentos de Saídas</h5>
            <div class="card-body row">
              <div align="left">
                <label class="form-label">
                  <h5>Filtros:</h5>
                </label>
              </div>
              <div class=" col-4 mb-3">
                <label for="exampleFormControlSelect1" class="form-label">Data Inicio:</label>
                <input type="date" name="" class="form-control">
                </br>
                <div class="mb-1" align="left">
                  <label class="form-label">
                    <button class="btn btn-primary">Aplicar Filtro</button>
                  </label>
              </div>
              </div>
              <div class="col-4 mb-3">
                <label for="exampleFormControlSelect1" class="form-label">Data Final:</label>
                <input type="date" name="" class="form-control">
              </div>

             <!-- Tabela -->

            

             <div class="table-responsive">

                  <h5 class="card-header" align="center">Lista de Saídas</h5>
                      <table class="table">
                        <thead>
                          <tr align="center">
                            <th>Data</th>
                            <th>Conta</th>
                            <th>Origem</th>
                            <th>Fonte Pagante</th>
                            <th>Forma de Pagamento</th>
                            <th>Valores</th>
                            <th>Ações</th>
                          </tr>
                        </thead>
                        <tbody>

                          <tr align="center">
                            <td>Teste</td>
                            <td>Teste</td>
                            <td>Teste</td>
                            <td>Teste</td>
                            <td>Teste</td>
                            <td>Teste</td>
                            <td>Teste</td>
                            

                          <tr align="center">
                            <td>Teste</td>
                            <td>Teste</td>
                            <td>Teste</td>
                            <td>Teste</td>
                            <td>Teste</td>
                            <td>Teste</td>
                            <td>Teste</td>
                            


    <!-- / Footer -->

    <div class="content-backdrop fade"></div>
  </div>
  <!-- Content wrapper -->
</div>
<!-- / Layout page -->
</div>