 <html
  lang="pt"
  class="light-style layout-menu-fixed"
>
<div class="layout-page">     
          <!-- Content wrapper -->
          <div class="content-wrapper">
            <!-- Content -->

            <div class="container-xxl flex-grow-1 container-p-y">
              <div class="row">
                <div class="col-lg-6 mb-4 order-0">
                  <div class="card h-100">
                    <div class="card-header d-flex align-items-center justify-content-between">
                      <h5 class="card-title m-0 me-2">Pendências</h5>
                    </div>
                    <div class="card-body">
                      <ul class="p-0 m-0">
                        <li class="d-flex mb-4 pb-1">
                          <div class="avatar flex-shrink-0 me-3">
                            <img src="../assets/img/icons/unicons/wallet.png" alt="User" class="rounded" />
                          </div>
                          <div class="d-flex w-100 flex-wrap align-items-center justify-content-between gap-2">
                            <div class="me-2">
                              <small class="text-muted d-block mb-1">Atualização Pendente</small>
                              <h6 class="mb-0"></h6>
                            </div>
                            <div class="user-progress d-flex align-items-center gap-1">
                              <h6 class="mb-0">0</h6>
                              <span class="text-muted">Atualizar</span>
                            </div>
                          </div>
                        </li>
                        <li class="d-flex mb-4 pb-1">
                          <div class="avatar flex-shrink-0 me-3">
                            <img src="../assets/img/icons/unicons/wallet.png" alt="User" class="rounded" />
                          </div>
                          <div class="d-flex w-100 flex-wrap align-items-center justify-content-between gap-2">
                            <div class="me-2">
                              <small class="text-muted d-block mb-1">Aprovação Pendente</small>
                              <h6 class="mb-0"></h6>
                            </div>
                            <div class="user-progress d-flex align-items-center gap-1">
                              <h6 class="mb-0">0</h6>
                              <span class="text-muted">Atualizar</span>
                            </div>
                          </div>
                        </li>
                        <li class="d-flex mb-4 pb-1">
                          <div class="avatar flex-shrink-0 me-3">
                            <img src="../assets/img/icons/unicons/wallet.png" alt="User" class="rounded" />
                          </div>
                          <div class="d-flex w-100 flex-wrap align-items-center justify-content-between gap-2">
                            <div class="me-2">
                              <small class="text-muted d-block mb-1">Envio de Documentos Pendente</small>
                              <h6 class="mb-0"></h6>
                            </div>
                            <div class="user-progress d-flex align-items-center gap-1">
                              <h6 class="mb-0">0</h6>
                              <span class="text-muted">Atualizar</span>
                            </div>
                          </div>
                        </li>
                        <li class="d-flex mb-4 pb-1">
                          <div class="avatar flex-shrink-0 me-3">
                            <img src="../assets/img/icons/unicons/wallet.png" alt="User" class="rounded" />
                          </div>
                          <div class="d-flex w-100 flex-wrap align-items-center justify-content-between gap-2">
                            <div class="me-2">
                              <small class="text-muted d-block mb-1">Pagamento Pendente</small>
                              <h6 class="mb-0"></h6>
                            </div>
                            <div class="user-progress d-flex align-items-center gap-1">
                              <h6 class="mb-0">0</h6>
                              <span class="text-muted">Atualizar</span>
                            </div>
                          </div>
                        </li>
                        <li class="d-flex mb-4 pb-1">
                          <div class="avatar flex-shrink-0 me-3">
                            <img src="../assets/img/icons/unicons/wallet.png" alt="User" class="rounded" />
                          </div>
                          <div class="d-flex w-100 flex-wrap align-items-center justify-content-between gap-2">
                            <div class="me-2">
                              <small class="text-muted d-block mb-1">Entradas Pendentes</small>
                              <h6 class="mb-0"></h6>
                            </div>
                            <div class="user-progress d-flex align-items-center gap-1">
                              <h6 class="mb-0">0</h6>
                              <span class="text-muted">Atualizar</span>
                            </div>
                          </div>
                        </li>
                        <li class="d-flex mb-4 pb-1">
                          <div class="avatar flex-shrink-0 me-3">
                            <img src="../assets/img/icons/unicons/wallet.png" alt="User" class="rounded" />
                          </div>
                          <div class="d-flex w-100 flex-wrap align-items-center justify-content-between gap-2">
                            <div class="me-2">
                              <small class="text-muted d-block mb-1">Entradas Pendentes</small>
                              <h6 class="mb-0"></h6>
                            </div>
                            <div class="user-progress d-flex align-items-center gap-1">
                              <h6 class="mb-0">0</h6>
                              <span class="text-muted">Atualizar</span>
                            </div>
                          </div>
                        </li>
                        <li class="d-flex mb-4 pb-1">
                          <div class="avatar flex-shrink-0 me-3">
                            <img src="../assets/img/icons/unicons/wallet.png" alt="User" class="rounded" />
                          </div>
                          <div class="d-flex w-100 flex-wrap align-items-center justify-content-between gap-2">
                            <div class="me-2">
                              <small class="text-muted d-block mb-1">Entradas Pendentes</small>
                              <h6 class="mb-0"></h6>
                            </div>
                            <div class="user-progress d-flex align-items-center gap-1">
                              <h6 class="mb-0">0</h6>
                              <span class="text-muted">Atualizar</span>
                            </div>
                          </div>
                        </li>
                      </ul>
                    </div>
                  </div>
                </div>
                <div class="col-lg-6 col-md-4 order-1">
                  <div class="row">
                    <div class="col-lg-4 col-md-12 col-6 mb-4">
                      <div class="card">
                        <div class="card-body">
                          <div class="card-title d-flex align-items-start justify-content-between">
                            <div class="avatar flex-shrink-0">
                              <img
                                src="../assets/img/icons/unicons/cc-primary.png"
                                alt="chart success"
                                class="rounded"
                              />
                            </div>
                          </div>
                          <span class="fw-semibold d-block mb-1">Faturado em Mãos</span>
                          <h3 class="card-title mb-2">R$ 0</h3>
                        </div>
                      </div>                   
                    </div>
                    <div class="col-lg-4 col-md-12 col-6 mb-4">
                      <div class="card">
                        <div class="card-body">
                          <div class="card-title d-flex align-items-start justify-content-between">
                            <div class="avatar flex-shrink-0">
                              <img
                                src="../assets/img/icons/unicons/cc-primary.png"
                                alt="chart primary"
                                class="rounded"
                              />
                            </div>
                          </div>
                          <span class="fw-semibold d-block mb-1">Aporte</span>
                          <h3 class="card-title mb-2">R$ 0</h3>
                        </div>
                      </div>
                      
                    </div>
                    <div class="col-lg-4 col-md-12 col-6 mb-4">
                      <div class="card">
                        <div class="card-body">
                          <div class="card-title d-flex align-items-start justify-content-between">
                            <div class="avatar flex-shrink-0">
                              <img
                                src="../assets/img/icons/unicons/cc-primary.png"
                                alt="chart success"
                                class="rounded"
                              />
                            </div>
                          </div>
                          <span class="fw-semibold d-block mb-1">Retirada</span>
                          <h3 class="card-title mb-2">R$ 0</h3>
                        </div>
                      </div>                   
                    </div>
                    <div class="col-lg-4 col-md-12 col-6 mb-4">
                      <div class="card">
                        <div class="card-body">
                          <div class="card-title d-flex align-items-start justify-content-between">
                            <div class="avatar flex-shrink-0">
                              <img
                                src="../assets/img/icons/unicons/cc-primary.png"
                                alt="chart success"
                                class="rounded"
                              />
                            </div>
                          </div>
                          <span class="fw-semibold d-block mb-1">Contas do Dia</span>
                          <h3 class="card-title mb-2">0</h3>
                        </div>
                      </div>                   
                    </div>
                    <div class="col-lg-4 col-md-12 col-6 mb-4">
                      <div class="card">
                        <div class="card-body">
                          <div class="card-title d-flex align-items-start justify-content-between">
                            <div class="avatar flex-shrink-0">
                              <img
                                src="../assets/img/icons/unicons/cc-primary.png"
                                alt="chart success"
                                class="rounded"
                              />
                            </div>
                          </div>
                          <span class="fw-semibold d-block mb-1">Contas em Atrazo</span>
                          <h3 class="card-title mb-2">0</h3>
                        </div>
                      </div>                   
                    </div>
                    <div class="col-lg-4 col-md-12 col-6 mb-4">
                      <div class="card">
                        <div class="card-body">
                          <div class="card-title d-flex align-items-start justify-content-between">
                            <div class="avatar flex-shrink-0">
                              <img
                                src="../assets/img/icons/unicons/cc-primary.png"
                                alt="chart success"
                                class="rounded"
                              />
                            </div>
                          </div>
                          <span class="fw-semibold d-block mb-1">Contas a Pagar</span>
                          <h3 class="card-title mb-2">0</h3>
                        </div>
                      </div>                   
                    </div>
                                                           
                  </div>
                </div>
            </div>
            <!-- Tabela -->
            <div class="card">
              <h5 class="card-header">Lista de Saidas Pendentes</h5>
              <div class="table-responsive text-nowrap">
                <table class="table table-striped ">
                  <thead>
                    <tr>
                      <th>Data</th>
                      <th>Conta</th>
                      <th>Origem</th>
                      <th>Fonte<br>Pg</th>
                      <th>Forma<br>Pg</th>
                      <th>Valor</th>
                      <th>Estagio</th>
                    </tr>
                  </thead>
                  <tbody >
                      
                      <?php foreach($this->view->tb_saidas as $index => $tb_saidas) { ?>
                      <tr id="saida_<?= $tb_saidas['id_saida'] ?>">
                      <td><?= $tb_saidas['data'] ?></td>
                      <td><?= $tb_saidas['conta_saida'] ?></td>
                      <td><?= $tb_saidas['origem_saida'] ?></td>
                      <td><?= $tb_saidas['fpagante_saida'] ?></td>
                      <td><?= $tb_saidas['fpagamento_saida'] ?></td>
                      <td>R$ <?= number_format( $tb_saidas['valor_saida'], 2, "," , ".") ?></td>
                      <?php 
                        switch ($tb_saidas['status_saida']) {
                            case 'Paga':
                                $cor = 'class="badge rounded-pill bg-label-primary"';
                                break;
                            case 'Atualização Pendente':
                                $cor = 'class="badge rounded-pill bg-label-secondary"';
                                break;
                            case 'Aprovação Pendente':
                                $cor = 'class="badge rounded-pill bg-label-success"';
                                break;
                            case 'Envio de Documentos Pendente':
                                $cor = 'class="badge rounded-pill bg-label-danger"';
                                break;
                            case 'Pagamento Pendente':
                                $cor = 'class="badge rounded-pill bg-label-warning"';
                                break;
                            case 'Paga sem Aprovação':
                                $cor = 'class="badge rounded-pill bg-label-info"';
                                break;
                            case 'Paga sem Aprovação Admin':
                                $cor = 'class="badge rounded-pill bg-label-dark"';
                                break;
                            case 'Aguardando Peças':
                                $cor = '#FF7F00';
                                break;
                            case 'Aprovado':
                                $cor = '#808080';
                                break;
                            default:
                                $cor = '#E0E4CC';
                                break;
                              } 

                              echo '<td><span '. $cor .'>' . $tb_saidas['status_saida'] . '</span> </td>';

                              ?>                      
                      </tr>
                      <?php } ?>
              
                  </tbody>
                </table>
              </div>
            </div>
          <!--Final Tabela-->  
                
